server:
  port: 8082

spring:
  application:
    name: trading-service
  cloud:
    nacos:
      discovery:
        enabled: false
        server-addr: 127.0.0.1:8848
        namespace: public
      config:
        enabled: false
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        import-check:
          enabled: false
  datasource:
    url: jdbc:mysql://192.168.100.36:3306/stock_investment?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: ${MYSQL_DB_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.100.145
    port: 6379
    database: 0

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

feign:
  sentinel:
    enabled: true

sentinel:
  transport:
    dashboard: 127.0.0.1:8080
  eager: true

management:
  endpoints:
    web:
      exposure:
        include: '*'